### ISSUE TITLE
Request - forking to Basho for stewardship 

### ISSUE THREAD

**Issue by mbbroberg** [tpjg/goriakpbc#98]
Hey @tpjg! This client is excellent. A few of us inside Basho would like to fork it and maintain it as an "official" library. Would you be comfortable with this collaboration? The intention is to continue to share this code in the open.

**Comment by tpjg** [comment]
Of course. Happy to see golang becoming an "official supported language", and especially by forking this library. Feel free to submit a PR changing the README and pointing to a new Basho supported location.

**Comment by christophermancini** [comment]
:+1 Thanks @tpjg. We are excited to start working with your library.

**Comment by danqing** [comment]
I'm curious about what the plans and roadmaps may look like for this. Any comments @mjbrender and @christophermancini? Thanks!

**Comment by christophermancini** [comment]
@danqing At this point, we don't have a clearly defined roadmap as we have been focusing on making improvements in other client libs. However, the ultimate goal is to make this lib officially supported by Basho, meaning it will be maintained by Basho staffers with current Riak release features and is eligible for technical support contracts.

**Comment by mjbrender** [comment]
Hey @danqing - +1 to @christophermancini's note. It will parallel the work we do on other supported libraries

**Comment by mjbrender** [comment]
^ mis-click turned into a close. I'm reopening until we update the README and outline some of our intentions.

**Comment by danqing** [comment]
Cool. Yeah I understand that you need to take care of other libraries too, but if you can at least share your plans etc., users of this library (e.g. me) can manage our expectations and also see if there's anything we can contribute while using it.

**Comment by christophermancini** [comment]
I absolutely understand your request, it's just that we have not developed a timeline yet so I don't have one to share. We are wrapping up other tasks as I said, then we will begin evaluating the code to determine what work we intend to compete on the lib to make it official. Until we finish looking over the code and determine the resources we have available to do the work, there is no way we could give a reasonable timeline. We are hopeful to begin reviewing the current codebase by the end of this quarter, possibly sooner. 

Like most software projects, we spend most of our time thinking about and designing the user interface. Since this isn't a rewrite of a library we already created (e.g. the PHP client), I expect that we will spend more time on this portion of the process. Which makes it even more difficult to set a timeline.

In the mean time, we would greatly appreciate any and all contributions you offer. That can include giving us your thoughts on the current user interface with maybe a comparison of another library where you really like the interface. You can even let us know what features or changes you would like to see completed. We would also love for you to contribute actual code by forking the lib and submitting a pull request but please first talk to us before performing a bunch of work. The worst thing is for you to make changes only to find out we had already made those changes or we decided to go in a different direction and just haven't pushed to Github yet.

**Comment by danqing** [comment]
Thanks @christophermancini !

Kinda unrelated, but I'm actually curious whether the riak docs are open source? I feel like there are quite some typos (not just spelling, but wrong sometimes), but it may be that I didn't understand it correctly. Wanted to at least get some clarifications.

**Comment by alexmoore** [comment]
Hey @danqing, the docs are open source:  https://github.com/basho/basho_docs.  Just file an issue / submit a PR if you find something wrong.  They're constantly being worked on, so I imagine some things get missed here and there over time.

**Comment by christophermancini** [comment]
Your quite welcome @danqing and thank you for asking!

**Comment by DAddYE** [comment]
@mjbrender is the official fork going to happen? I can't see it in the basho org.

**Comment by quasor** [comment]
@christophermancini can you comment on your plans? it seems you've changed you mind.

**Comment by christophermancini** [comment]
@quasor @DAddYE Sorry for the delayed response. After reviewing this library in depth as well as others, we decided to write our own so that we can maintain consistency across all of our libraries with respect to api design. This will allow our users to hop from language to language with lower barriers of entry. We released this rewrite to beta recently and are expecting to have it all polished by early - mid September.

The project can be found @ https://github.com/basho/riak-go-client

**Comment by quasor** [comment]
:+1:

**Comment by mjbrender** [comment]
Sorry - missed your tag @DAddYE. As @christophermancini noted, we've got it over on Basho proper now that it's in Beta. I've been tweeting out its support and we [announced it on the riak-user mailing list](http://lists.basho.com/mailman/listinfo/riak-users_lists.basho.com) (which I highly recommend you join if you haven't!). 

I owe a PR to this doc -- it's on the way.

**Comment by mjbrender** [comment]
PR #103 notes that we've got this covered! I'm pumped to see your work running as the core of us delivering a new client library to our community. @tpjg and @danqing - I really hope to see your names in our new repo: https://github.com/basho/riak-go-client

If any of you have ideas on what example code we could build together, I welcome brainstorms over here: https://github.com/basho-labs/the-riak-community/issues
